var RightSection = {
    canvasTileWidth : 44,
    canvasTileHeight : 44,
    currentTile : null, // SCTile
    currentTileIndex : 0,

    switchTo : function(elementID) {},
    onButtonClick : function() {},
    onTilesetChange : function() {},
    onTileClick : function() {},
    deselectTiles : function() {},
    onSCMapAPILoad : function() {},
    selectMode : function(modeName) {},
    selectTileset : function(tilesetName, isUserSelection) {},
    selectTile : function(tileName) {},
    selectTileByIndex : function(index) {},
    addTiles : function() {},
    refreshLocationExample : function() {},
    onWaitValueChange : function() {},
    refreshWaitRefData : function() {},
    onPlayButtonClick : function() {},
    addTurn : function() {},
    insertTurn : function() {},
    copyTurn : function() {},
    invertTurn : function() {},
    deleteTurn : function() {},
    changeTurn : function(turnNumber) {},
    onCurrentTurnTextChange : function() {},
    onToPrevClick : function() {},
    onToNextClick : function() {},
    onToFirstClick : function() {},
    onToLastClick : function() {},
    onOption1RadioClick : function() {},
    onOption2RadioClick : function() {},
    onBombUnits1Change : function() {},
    onBombUnits2Change : function() {},
    onBombUnits3Change : function() {}
};